name: gha_basic:GitHub Action flow to Docker hub 

on:
  workflow_dispatch:


jobs:
  #Definition of the system to be installed
  build-push-images:
    name: Budowa i publikacja obrazw na repozytorium
    runs-on: ubuntu-latest

    steps:
      #Downloading the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3
      #Buildx configuration
      - name: Buildx set-up
        uses: docker/setup-buildx-action@v2
      #QEMU configuration
      - name: Docker Setum QEMU
        uses: docker/setup-qemu-action@v2
      #Login to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #Build and publish Docker images
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/arm64/v8,linux/amd64
          context: ./
          file: ./dockerfile
          push: true
          tags: |
            kowalczykp13/lab:lab2
          
